import Footer from './components/footer/Footer'
import NavBar from './components/navbar/NavBar'
import './globals.css'
import { Inter, Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <div className="container">
          <NavBar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  )
}